name: Update submodules
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️ startai
        uses: actions/checkout@v4
        with:
          repository: khulnasoft/startai
          token: ${{ secrets.STARTAI_BRANCH_TOKEN }}
          submodules: recursive

      - name: Update submodules
        run: |
          git config --global user.email "startai.branch@lets-khulnasoft.com"
          git config --global user.name "startai-branch"
          git submodule update --remote docs/demos
          git add .
          git commit -m "Update demos 🤖"
          git push origin main
